### PR TITLE
Support new language types

### PR DESCRIPTION
**Pull request by anchovie91471**
- Load types.json from Github repository URL
- Create $types in constructor from json file

### CODE REVIEW

**Review by joshreisner — APPROVED** [review]
it's a cool idea to live-fetch the meeting types - i worry a little about the latency and adding a step that could fail, but i suppose you'll get a report from sentry if something goes wrong

i think a composer package would be a great solution for the long term

**Review by joshreisner — APPROVED** [review]
out of curiosity, what's the advantage of changing the headings to spans?

**Comment by anchovie91471** [comment]
It wasn't so much an advantage as I had problems getting headings to show up in the right font in the PDF (they would look fine in browser and then be Times New Roman when the PDF was output, whether Serif or Sans was chosen)

I honestly don't know why this was happening. It seemed a quirk of DOMPdF when loading custom fonts but only failed for the H1 and H3 tags. 🤷🏻‍♂️

It took a bunch of experimentation to get the right Serif font and the problems I was seeing could have been related to bad fonts. I can change them back and see what happens, but since a PDF was the final output, semantic HTML didn't seem important enough to worry about it.

**Comment by joshreisner** [comment]
yep, i agree,l thanks!

**Pull request merged**
